version: "3"

services:
  
  db:
    container_name: itc_db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data/:/var/lib/postgresql/data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    container_name: ITCdevs
    build:
      context: .
    ports:
      - "2000:2000"
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    networks:
      - my-network
    depends_on:
      - db

  nginx:
    container_name: ITCdevs_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
      - ./media/:/media
    depends_on:
      - db
      - web
    networks:
     - my-network
  

volumes:
  media:
  static:
  postgres_data:

networks:
  my-network:






