# Generated by Django 3.2.7 on 2023-02-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_aboutus_ad_connection_eventlent_freevacancy_getconsult_image_ourpartner_projects_questionanswer_staf'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(default=None, max_length=127, verbose_name='Город разработчика'),
        ),
        migrations.AddField(
            model_name='staff',
            name='city_en',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Город разработчика'),
        ),
        migrations.AddField(
            model_name='staff',
            name='city_ru',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Город разработчика'),
        ),
    ]
